### ISSUE TITLE
Como es la configuracion para produccion.

### ISSUE THREAD

**Issue by Corobori** [TransbankDevelopers/transbank-sdk-dotnet-webpay-example#10]
En tbk-normal.aspx se carga la configuracion con var configuration = Configuration.ForTestingWebpayPlusNormal(); asumo que "ForTestingWebpayPlusNormal"  es para prueba. ¿ Con que reemplazo eso para pasar en ambiente de produccion ?

**Comment by ffiebig** [comment]
Sorry que esta pregunta haya quedado olvidada, si tienes alguna duda en el futuro es mejor que acudas al Slack de la comunidad, por alla atendemos preguntas de Lunes a Viernes de maner mucho más expedita.

https://join-transbankdevelopers-slack.herokuapp.com/
