### ISSUE TITLE
Carpeta certificates

### ISSUE THREAD

**Issue by Corobori** [TransbankDevelopers/transbank-sdk-dotnet-webpay-example#9]
¿ A que sirve la carpeta certificates ? 
La veo siendo utilizada solamente en tbk-complete.aspx, lo cual por lo demas no funciona porque requiere un certificado referenciado en cert-complete.cs que no se encuentra: 597020000545.pfx

**Comment by ffiebig** [comment]
Perdón que haya quedada olvidada la pregunta. Te recomiendo que vayas al Slack de la comunidad si en el futuro tienes una pregunta.

https://join-transbankdevelopers-slack.herokuapp.com/
